/**
 * FILE IS GENERATED BY CODEGEN SCRIPT, WHICH IMPLEMENTS ALL 
 * COMPONENT TYPES. DO NOT EDIT THIS FILE DIRECTLY.
 * 
 * Implements a "prototype" which is a cached base configuration
 * for a vehicle. This is used to create new vehicles. Rough process
 * involves using prototype as base then injecting specific data
 * for vehicle creation.
 * 
 *               Spawning                 Spawning from
 *              from item:                  save data
 * 
 *              prototype                   prototype 
 *                  |                           |     
 *                  |                           |     
 *     item         v              save         v     
 *     data ------> +              data ------> +     
 *                  |                           |     
 *                  |                           |     
 *    player        v                           |     
 *    event ------> +                           |     
 *     data         |                           |     
 *                  |                           |     
 *                  v                           v     
 *              components                  components
 */

package phonon.xv.core

import java.nio.file.Path
import java.util.EnumSet
import java.util.logging.Logger
import org.tomlj.Toml
import org.tomlj.TomlTable
import phonon.xv.component.*


/**
 * VehiclePrototype defines elements in a vehicle. Used as a base
 * object to create new vehicles.
 */
public data class VehiclePrototype(
    val name: String,
    val elements: Array<VehicleElementPrototype>,
) {
    companion object {
        /**
         * Try to load a vehicle prototype from a toml file.
         * If any of the internal elements fails to parse, this will
         * print an error and return a null.
         */
        public fun fromTomlFile(source: Path, logger: Logger? = null): VehiclePrototype? {
            try {
                val toml = Toml.parse(source)

                val name = toml.getString("name") ?: ""

                // if this contains an elements table, parse each element
                // else, parse entire doc as single toml table
                val elements: Array<VehicleElementPrototype> = toml.getArray("elements")?.let { elems ->
                    ( 0 until elems.size() )
                    .map { i -> VehicleElementPrototype.fromToml(elems.getTable(i)) }
                    .toTypedArray()
                } ?: arrayOf(VehicleElementPrototype.fromToml(toml))

                return VehiclePrototype(name, elements)
            } catch (e: Exception) {
                logger?.warning("Failed to parse landmine file: ${source.toString()}, ${e}")
                e.printStackTrace()
                return null
            }
        }
    }
}

/**
 * VehicleElementPrototype defines a vehicle element's initial components.
 * Contains all possible components, but only the ones in layout should
 * be non-null.
 */
public data class VehicleElementPrototype(
    val name: String,
    val parent: String?,
    val layout: EnumSet<VehicleComponentType>,
    val fuel: FuelComponent? = null,
    val gunTurret: GunTurretComponent? = null,
    val health: HealthComponent? = null,
    val landMovementControls: LandMovementControlsComponent? = null,
    val model: ModelComponent? = null,
    val seats: SeatsComponent? = null,
    val seatsRaycast: SeatsRaycastComponent? = null,
    val transform: TransformComponent? = null,
) {
    companion object {
        public fun fromToml(toml: TomlTable, logger: Logger? = null): VehicleElementPrototype {
            // element built-in properties
            val name = toml.getString("name") ?: ""
            val parent = toml.getString("parent")
            
            // all possible components to be parsed
            var fuel: FuelComponent? = null
            var gunTurret: GunTurretComponent? = null
            var health: HealthComponent? = null
            var landMovementControls: LandMovementControlsComponent? = null
            var model: ModelComponent? = null
            var seats: SeatsComponent? = null
            var seatsRaycast: SeatsRaycastComponent? = null
            var transform: TransformComponent? = null

            // parse components from matching keys in toml
            val layout = EnumSet.noneOf(VehicleComponentType::class.java)
            val keys = toml.keySet()
            for ( k in keys ) {
                when ( k ) {
                    "name", "parent" -> continue
                    "fuel" -> {
                        layout.add(VehicleComponentType.FUEL)
                        fuel = FuelComponent.fromToml(toml.getTable(k)!!, logger)
                    }
                    "gun_turret" -> {
                        layout.add(VehicleComponentType.GUN_TURRET)
                        gunTurret = GunTurretComponent.fromToml(toml.getTable(k)!!, logger)
                    }
                    "health" -> {
                        layout.add(VehicleComponentType.HEALTH)
                        health = HealthComponent.fromToml(toml.getTable(k)!!, logger)
                    }
                    "land_movement_controls" -> {
                        layout.add(VehicleComponentType.LAND_MOVEMENT_CONTROLS)
                        landMovementControls = LandMovementControlsComponent.fromToml(toml.getTable(k)!!, logger)
                    }
                    "model" -> {
                        layout.add(VehicleComponentType.MODEL)
                        model = ModelComponent.fromToml(toml.getTable(k)!!, logger)
                    }
                    "seats" -> {
                        layout.add(VehicleComponentType.SEATS)
                        seats = SeatsComponent.fromToml(toml.getTable(k)!!, logger)
                    }
                    "seats_raycast" -> {
                        layout.add(VehicleComponentType.SEATS_RAYCAST)
                        seatsRaycast = SeatsRaycastComponent.fromToml(toml.getTable(k)!!, logger)
                    }
                    "transform" -> {
                        layout.add(VehicleComponentType.TRANSFORM)
                        transform = TransformComponent.fromToml(toml.getTable(k)!!, logger)
                    }
                    else -> logger?.warning("Unknown key in vehicle element: $k")
                }
            }
            
            return VehicleElementPrototype(
                name,
                parent,
                layout,
                fuel,
                gunTurret,
                health,
                landMovementControls,
                model,
                seats,
                seatsRaycast,
                transform,
            )
        }
    }
}