/**
 * FILE IS GENERATED BY CODEGEN SCRIPT, WHICH IMPLEMENTS ALL 
 * COMPONENT TYPES. DO NOT EDIT THIS FILE DIRECTLY.
 * 
 * Implements a "prototype" which is a cached base configuration
 * for a vehicle. This is used to create new vehicles. Rough process
 * involves using prototype as base then injecting specific data
 * for vehicle creation.
 * 
 *               Spawning                 Spawning from
 *              from item:                  save data
 * 
 *              prototype                   prototype 
 *                  |                           |     
 *                  |                           |     
 *     item         v              save         v     
 *     data ------> +              data ------> +     
 *                  |                           |     
 *                  |                           |     
 *    player        v                           |     
 *    event ------> +                           |     
 *     data         |                           |     
 *                  |                           |     
 *                  v                           v     
 *              components                  components
 */

package phonon.xv.core

import java.util.EnumSet
import phonon.xv.component.*


/**
 * Prototype contains a definition of a vehicle element's initial
 * components. Contains all possible components, but only the ones
 * in layout should be non-null.
 */
public data class VehiclePrototype(
    val layout: EnumSet<VehicleComponentType>,
    val fuel: FuelComponent? = null,
    val health: HealthComponent? = null,
    val land_movement_controls: LandMovementControlsComponent? = null,
    val model: ModelComponent? = null,
    val transform: TransformComponent? = null,
) {

}