/**
 * FILE IS GENERATED BY CODEGEN SCRIPT, WHICH GENERATES SERIALIZATION
 * AND DERSERIALIZATION CODE. DO NOT EDIT THIS FILE DIRECTLY.
 *
 * Implements extension functions for VehicleElement and Vehicle which
 * serializes these objects into JsonObjects for use in the saving and
 * loading extension functions.
 *
 * JSON schema for vehicles: (Quotes for field names excluded)
 * ========saved_vehicles.json===========
 * {
 *    vehicles: [
 *        {
 *            uuid: "uuid here",
 *            prototype: "test_vehicle",
 *            elements: {
 *                elementPrototype1: {
 *                    uuid: "uuid here",
 *                    components: {
 *                        fuel: {
 *                            current = 0
 *                        },
 *                        health: {
 *                            current = 20
 *                        },
 *                        landMovementControls: {
 *                            speed: 10.0,
 *                            yawRotationSpeed: 20.0
 *                        },
 *                        transform: {
 *                            world: "world",
 *                            x: 20.0,
 *                            y: 81.0,
 *                            z: 20.0
 *                        }
 *                    }
 *                },
 *                elementPrototype2: {
 *                    uuid: "uuid here",
 *                    components: {
 *                        fuel: {
 *                            current = 0
 *                        },
 *                        health: {
 *                            current = 20
 *                        },
 *                        landMovementControls: {
 *                            speed: 10.0,
 *                            yawRotationSpeed: 20.0
 *                        },
 *                        transform: {
 *                            world: "world",
 *                            x: 20.0,
 *                            y: 81.0,
 *                            z: 20.0
 *                        }
 *                    }
 *                }
 *            }
 *        }
 *    ]
 * }
 * =======FILE END=========
 * Note that each element stored in the `elements` field is indexed
 * by the name of its prototype. The object itself does not actually contain any name.
 * The save state of each component is structured similarly. They are identified
 * by the field they are stored in, rather than their actual contents. This is
 * simply for faster
 */

package phonon.xv.core

import com.google.gson.Gson
import com.google.gson.GsonBuilder
import com.google.gson.JsonArray
import com.google.gson.JsonObject
import com.google.gson.JsonParser
import com.google.gson.JsonPrimitive
import phonon.xv.XV
import phonon.xv.component.*
import phonon.xv.system.CreateVehicleReason
import phonon.xv.system.CreateVehicleRequest
import phonon.xv.system.systemCreateVehicle
import phonon.xv.util.file.readJson
import phonon.xv.util.file.writeJson
import java.io.FileReader
import java.io.FileWriter
import java.nio.file.Path
import java.util.logging.Logger

/**
 * Extension function to serialize VehicleElement to
 * a JsonObject. XV instance is needed to pass into
 * VehicleElement toJson function.
 */
fun VehicleElement.toJson(xv: XV): JsonObject {
    val json = JsonObject()
    json.addProperty("uuid", this.uuid.toString())
    val componentsJson = JsonObject()
    val archetype = xv.storage.lookup[this.layout]!!
    for ( c in this.layout ) {
        // serialize component state in json
        val cJson = when ( c ) {
            VehicleComponentType.AMMO -> archetype.getComponent<AmmoComponent>(this.id)!!.toJson()
            VehicleComponentType.FUEL -> archetype.getComponent<FuelComponent>(this.id)!!.toJson()
            VehicleComponentType.GUN_BARREL -> archetype.getComponent<GunBarrelComponent>(this.id)!!.toJson()
            VehicleComponentType.GUN_TURRET -> archetype.getComponent<GunTurretComponent>(this.id)!!.toJson()
            VehicleComponentType.HEALTH -> archetype.getComponent<HealthComponent>(this.id)!!.toJson()
            VehicleComponentType.LAND_MOVEMENT_CONTROLS -> archetype.getComponent<LandMovementControlsComponent>(this.id)!!.toJson()
            VehicleComponentType.MODEL -> archetype.getComponent<ModelComponent>(this.id)!!.toJson()
            VehicleComponentType.SEATS -> archetype.getComponent<SeatsComponent>(this.id)!!.toJson()
            VehicleComponentType.SEATS_RAYCAST -> archetype.getComponent<SeatsRaycastComponent>(this.id)!!.toJson()
            VehicleComponentType.SPAWN -> archetype.getComponent<SpawnComponent>(this.id)!!.toJson()
            VehicleComponentType.TRANSFORM -> archetype.getComponent<TransformComponent>(this.id)!!.toJson()
            else -> throw Exception("Unknown component type: $c")
        }
        // add this json to our components object
        if ( cJson !== null ) {
            // just get storage string of
            val propertyLabel = when ( c ) {
                VehicleComponentType.AMMO -> "ammo"
                VehicleComponentType.FUEL -> "fuel"
                VehicleComponentType.GUN_BARREL -> "gunBarrel"
                VehicleComponentType.GUN_TURRET -> "gunTurret"
                VehicleComponentType.HEALTH -> "health"
                VehicleComponentType.LAND_MOVEMENT_CONTROLS -> "landMovementControls"
                VehicleComponentType.MODEL -> "model"
                VehicleComponentType.SEATS -> "seats"
                VehicleComponentType.SEATS_RAYCAST -> "seatsRaycast"
                VehicleComponentType.SPAWN -> "spawn"
                VehicleComponentType.TRANSFORM -> "transform"
                else -> throw Exception("Unknown component type: $c")
            }
            // add parsed component state to our component object
            componentsJson.add(propertyLabel, cJson)
        }
    }
    json.add("components", componentsJson)
    return json
}

fun Vehicle.toJson(xv: XV): JsonObject {
    val json = JsonObject()
    json.addProperty("uuid", this.uuid.toString())
    json.addProperty("prototype", this.prototype.name)
    val elementsJson = JsonObject()
    for ( elt in this.elements ) {
        try {
            elementsJson.add(elt.prototype.name, elt.toJson(xv))
        } catch ( e: Exception ) {
            throw Exception("Encountered an exception while serializing VehicleElement " +
                    "with UUID ${elt.uuid} and prototype ${elt.prototype.name}.\n$e")
        }
    }
    json.add("elements", elementsJson)
    return json
}

fun XV.serializeVehicles(logger: Logger? = null): JsonObject {
    val xv = this
    // set up json stuff
    val json = JsonObject()
    val vehiclesArrayJson = JsonArray()
    for (vehicle in xv.vehicleStorage) {
        try {
            vehiclesArrayJson.add(vehicle.toJson(xv))
        } catch ( e: Exception ) {
            logger?.severe("Encountered an exception while serializing vehicle with UUID " +
                    "${vehicle.uuid} and prototype ${vehicle.prototype.name}.\n$e")
        }
    }
    json.add("vehicles", vehiclesArrayJson)
    return json
}

fun XV.deserializeVehicles(json: JsonObject, logger: Logger? = null) {
    val xv = this
    val vehiclesArrayJson = json["vehicles"].asJsonArray
    for ( vehicleJson in vehiclesArrayJson ) {
        try {
            if ( vehicleJson is JsonObject ) {
                val prototype = xv.vehiclePrototypes[ vehicleJson["prototype"]!!.asString ]!!

                xv.createRequests.add(
                        CreateVehicleRequest(
                                prototype,
                                CreateVehicleReason.LOAD,
                                json = vehicleJson
                        )
                )
            } else {
                throw Exception("Encountered malformed JSON structure while loading save data from JSON: ${vehicleJson}")
            }
        } catch ( e: Exception ) {
            logger?.severe("Encountered unexpected exception while loading Vehicle JSON: $e")
        }
    }
}

/**
 * Save all vehicles as json. Called during shutdown/restart.
 * This function is intended to be run on the main thread, so
 * while it is backup safe,
 */
fun XV.saveVehicles(saveTo: Path, logger: Logger? = null) {
    try {
        val xv = this
        val savedVehicles = xv.serializeVehicles(xv.logger)
        writeJson(
                savedVehicles,
                xv.config.pathSave,
                xv.config.savePrettyPrintingJson
        )
    } catch ( e: Exception ) {
        logger?.severe("Encountered an issue saving vehicle data from file: $saveTo")
    }
}

/**
 * Load all vehicles from json file. Called during
 * startup/restart. This can also be called during runtime,
 * but make sure to clear all the storages first!
 */
fun XV.loadVehicles(readFrom: Path, logger: Logger? = null) {
    try {
        val xv = this
        // IO
        val loadedVehicles = readJson(xv.config.pathSave)
        if ( loadedVehicles !== null )
            xv.deserializeVehicles(loadedVehicles, xv.logger)
    } catch ( e: Exception ) {
        logger?.severe("Encountered an issue loading vehicle data from file: $readFrom")
    }
}

/**
 * Just a simple util function to execute all create requests
 * in queue, used to spawn in vehicles loaded in from IO
 */
fun XV.flushCreateQueue() {
    systemCreateVehicle(storage, createRequests)
}