/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package phonon.xv.test.core

import kotlin.test.Test
import kotlin.test.assertNotNull
import kotlin.test.assertNull
import kotlin.test.assertEquals
import kotlin.test.fail

import java.util.EnumSet
import phonon.xv.component.*
import phonon.xv.core.*
import phonon.xv.core.iter.*


public class ArchetypeTest() {

    /**
     * Test basic insertion and removal of archetypes
     */
    @Test
    fun basicInsertRemove() {
        val archetype = ArchetypeStorage(
            EnumSet.of(
                VehicleComponentType.FUEL,
            ),
            100,
        )

        for ( i in 0..3 ) {
            val fuel = VehicleComponents(
                layout = EnumSet.of(
                    VehicleComponentType.FUEL,
                ),
                fuel = FuelComponent(420, i),
            )
            archetype.insert(i, fuel)
        }

        assertEquals(4, archetype.size)

        // verify swap remove
        archetype.free(0)
        assertEquals(3, archetype.size)
        assertEquals(3, archetype.fuelView!![0].max)
        archetype.free(1)
        assertEquals(2, archetype.size)
        assertEquals(2, archetype.fuelView!![1].max)
        archetype.free(2)
        assertEquals(1, archetype.size)
        assertEquals(3, archetype.fuelView!![0].max)
        archetype.free(3)

        assertEquals(0, archetype.size)
    }
    
    /**
     * Test inserting to limit and failing.
     */
    @Test
    fun insertToCapacity() {
        val capacity = 100

        val archetype =ArchetypeStorage(
            EnumSet.of(
                VehicleComponentType.FUEL,
            ),
            capacity,
        )

        for ( i in 0..200 ) {
            val fuel = VehicleComponents(
                layout = EnumSet.of(
                    VehicleComponentType.FUEL,
                ),
                fuel = FuelComponent(420, i),
            )
            archetype.insert(i, fuel)
        }

        assertEquals(100, archetype.size)
    }

    /**
     * Test iterating across archetypes.
     */
    @Test
    fun iterator() {
        // manually insert archetypes
        val components = ComponentsStorage(1000)
        components.archetypes.add(ArchetypeStorage(
            EnumSet.of(
                VehicleComponentType.LAND_MOVEMENT_CONTROLS,
                VehicleComponentType.TRANSFORM,
            ),
            16,
        ))
        components.archetypes.add(ArchetypeStorage(
            EnumSet.of(
                VehicleComponentType.FUEL,
                VehicleComponentType.LAND_MOVEMENT_CONTROLS,
                VehicleComponentType.TRANSFORM,
            ),
            16,
        ))
        components.archetypes.add(ArchetypeStorage(
            EnumSet.of(
                VehicleComponentType.FUEL,
                VehicleComponentType.TRANSFORM,
            ),
            16,
        ))

        // no health component
        val iterHealth = ComponentTuple1.query<HealthComponent>(components)
        assertEquals(false, iterHealth.hasNext())

        for ( (_, _, _) in ComponentTuple2.query<LandMovementControlsComponent, TransformComponent>(components) ) {
            fail("ComponentTuple Iterator should not have any elements")
        }

        // manually insert fuel components, then test iter across archetypes
        // this needs to be changed when archetypes are properly implemented
        components.archetypes[1].fuel!!.add(FuelComponent(1, 1))
        components.archetypes[1].fuel!!.add(FuelComponent(2, 2))
        components.archetypes[1].size = 2
        components.archetypes[2].fuel!!.add(FuelComponent(3, 3))
        components.archetypes[2].size = 1

        val fuelExpected = listOf(1, 2, 3)
        var count = 0

        for ( (i, v) in ComponentTuple1.query<FuelComponent>(components).withIndex() ) {
            // println("i: $i, v: $v")
            val (_, fuel) = v
            assertEquals(fuelExpected[i], fuel.current)
            count += 1
        }

        assertEquals(3, count, "ComponentTuple Iterator should have 3 elements")
    }

}